export const NAV_TO = "NAV_TO";
export const SET_ROUTE = "SET_ROUTE";

export const GET_ALL_PARTIES_SEND = "GET_ALL_PARTIES_SEND";
export const GET_ALL_PARTIES_FAILED = "GET_ALL_PARTIES_FAILED";
export const GET_ALL_PARTIES_SUCCESS = "GET_ALL_PARTIES_SUCCESS";

export const CREATE_PARTY_SEND = "CREATE_PARTY_SEND";
export const CREATE_PARTY_FAILED = "CREATE_PARTY_FAILED";
export const CREATE_PARTY_SUCCESS = "CREATE_PARTY_SUCCESS";

export const CHANGE_CREATE_PARTY_TITLE = "CHANGE_CREATE_PARTY_TITLE";
export const CHANGE_CREATE_PARTY_DESCRIPTION = "CHANGE_CREATE_PARTY_DESCRIPTION";
export const CHANGE_CREATE_PARTY_IDEOLOGY = "CHANGE_CREATE_PARTY_IDEOLOGY";

export const SHOW_CREATE_MODAL = "SHOW_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";

export const CHANGE_CREATE_USER_NAME = "CHANGE_CREATE_USER_NAME";
export const CHANGE_CREATE_USER_LAST_NAME = "CHANGE_CREATE_USER_LAST_NAME";
export const CHANGE_CREATE_USER_STATUS = "CHANGE_CREATE_USER_STATUS";

export const CREATE_USER_SEND = "CREATE_USER_SEND";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const GET_ALL_USERS_SEND = "GET_ALL_USERS_SEND";
export const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

export const SHOW_CREATE_USER_MODAL = "SHOW_CREATE_USER_MODAL";
export const HIDE_CREATE_USER_MODAL = "HIDE_CREATE_USER_MODAL";

export const GET_EMPTY_USERS_SEND = "GET_EMPTY_USERS_SEND";
export const GET_EMPTY_USERS_FAILED = "GET_EMPTY_USERS_FAILED";
export const GET_EMPTY_USERS_SUCCESS = "GET_EMPTY_USERS_SUCCESS";

export const ADD_USER_SEND = "ADD_USER_SEND";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const GET_ALL_USERS_PARTY_SEND = "GET_ALL_USERS_PARTY_SEND";
export const GET_ALL_USERS_PARTY_FAILED = "GET_ALL_USERS_PARTY_FAILED";
export const GET_ALL_USERS_PARTY_SUCCESS = "GET_ALL_USERS_PARTY_SUCCESS";

export const DELETE_USER_PARTY_SEND = "DELETE_USER_PARTY_SEND";
export const DELETE_USER_PARTY_FAILED = "DELETE_USER_PARTY_FAILED";
export const DELETE_USER_PARTY_SUCCESS = "DELETE_USER_PARTY_SUCCESS";