export const NAV_TO = "NAV_TO";
export const SET_ROUTE = "SET_ROUTE";

export const GET_ALL_PARTIES_SEND = "GET_ALL_PARTIES_SEND";
export const GET_ALL_PARTIES_FAILED = "GET_ALL_PARTIES_FAILED";
export const GET_ALL_PARTIES_SUCCESS = "GET_ALL_PARTIES_SUCCESS";

export const CREATE_PARTY_SEND = "CREATE_PARTY_SEND";
export const CREATE_PARTY_FAILED = "CREATE_PARTY_FAILED";
export const CREATE_PARTY_SUCCESS = "CREATE_PARTY_SUCCESS";

export const CHANGE_CREATE_PARTY_TITLE = "CHANGE_CREATE_PARTY_TITLE";
export const CHANGE_CREATE_PARTY_DESCRIPTION = "CHANGE_CREATE_PARTY_DESCRIPTION";
export const CHANGE_CREATE_PARTY_IDEOLOGY = "CHANGE_CREATE_PARTY_IDEOLOGY";

export const SHOW_CREATE_MODAL = "SHOW_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";

export const CHANGE_CREATE_USER_NAME = "CHANGE_CREATE_USER_NAME";
export const CHANGE_CREATE_USER_LAST_NAME = "CHANGE_CREATE_USER_LAST_NAME";
export const CHANGE_CREATE_USER_STATUS = "CHANGE_CREATE_USER_STATUS";

export const CREATE_USER_SEND = "CREATE_USER_SEND";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const GET_ALL_USERS_SEND = "GET_ALL_USERS_SEND";
export const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

export const SHOW_CREATE_USER_MODAL = "SHOW_CREATE_USER_MODAL";
export const HIDE_CREATE_USER_MODAL = "HIDE_CREATE_USER_MODAL";

export const GET_EMPTY_USERS_SEND = "GET_EMPTY_USERS_SEND";
export const GET_EMPTY_USERS_FAILED = "GET_EMPTY_USERS_FAILED";
export const GET_EMPTY_USERS_SUCCESS = "GET_EMPTY_USERS_SUCCESS";

export const ADD_USER_SEND = "ADD_USER_SEND";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const GET_ALL_USERS_PARTY_SEND = "GET_ALL_USERS_PARTY_SEND";
export const GET_ALL_USERS_PARTY_FAILED = "GET_ALL_USERS_PARTY_FAILED";
export const GET_ALL_USERS_PARTY_SUCCESS = "GET_ALL_USERS_PARTY_SUCCESS";

export const DELETE_USER_PARTY_SEND = "DELETE_USER_PARTY_SEND";
export const DELETE_USER_PARTY_FAILED = "DELETE_USER_PARTY_FAILED";
export const DELETE_USER_PARTY_SUCCESS = "DELETE_USER_PARTY_SUCCESS";

export const GET_ALL_LAWS_SEND = "GET_ALL_LAWS_SEND";
export const GET_ALL_LAWS_FAILED = "GET_ALL_LAWS_FAILED";
export const GET_ALL_LAWS_SUCCESS = "GET_ALL_LAWS_SUCCESS";

export const CREATE_LAW_SEND = "CREATE_LAW_SEND";
export const CREATE_LAW_FAILED = "CREATE_LAW_FAILED";
export const CREATE_LAW_SUCCESS = "CREATE_LAW_SUCCESS";

export const DELETE_LAW_SEND = "DELETE_LAW_SEND";
export const DELETE_LAW_FAILED = "DELETE_LAW_FAILED";
export const DELETE_LAW_SUCCESS = "DELETE_LAW_SUCCESS";

export const SEARCH_LAWS_SEND = "SEARCH_LAWS_SEND";
export const SEARCH_LAWS_FAILED = "SEARCH_LAWS_FAILED";
export const SEARCH_LAWS_SUCCESS = "SEARCH_LAWS_SUCCESS";

export const SET_SEARCHING_LAWS = "SET_SEARCHING_LAWS";

export const SHOW_CREATE_LAW_MODAL = "SHOW_CREATE_LAW_MODAL";
export const HIDE_CREATE_LAW_MODAL = "HIDE_CREATE_LAW_MODAL";

export const CHANGE_CREATELAW_TITLE = "CHANGE_CREATELAW_TITLE";
export const CHANGE_CREATELAW_BODY = "CHANGE_CREATELAW_BODY";
export const CHANGE_CREATELAW_CREATOR = "CHANGE_CREATELAW_CREATOR";

export const GET_ALL_NEWS_SEND = "GET_ALL_NEWS_SEND";
export const GET_ALL_NEWS_FAILED = "GET_ALL_NEWS_FAILED";
export const GET_ALL_NEWS_SUCCESS = "GET_ALL_NEWS_SUCCESS";

export const CREATE_NEWS_SEND = "CREATE_NEWS_SEND";
export const CREATE_NEWS_FAILED = "CREATE_NEWS_FAILED";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";

export const DELETE_NEWS_SEND = "DELETE_NEWS_SEND";
export const DELETE_NEWS_FAILED = "DELETE_NEWS_FAILED";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";

export const SHOW_CREATE_NEWS_MODAL = "SHOW_CREATE_NEWS_MODAL";
export const HIDE_CREATE_NEWS_MODAL = "HIDE_CREATE_NEWS_MODAL";

export const CHANGE_CREATE_NEWS_TITLE = "CHANGE_CREATE_NEWS_TITLE";
export const CHANGE_CREATE_NEWS_BODY = "CHANGE_CREATE_NEWS_BODY";
export const CHANGE_CREATE_NEWS_CREATOR = "CHANGE_CREATE_NEWS_CREATOR";

export const SET_PARTY_RATING_SEND = "SET_PARTY_RATING_SEND";
export const SET_PARTY_RATING_FAILED = "SET_PARTY_RATING_FAILED";
export const SET_PARTY_RATING_SUCCESS = "SET_PARTY_RATING_SUCCESS";

export const SHOW_SET_RATING_MODAL = "SHOW_SET_RATING_MODAL";
export const HIDE_SET_RATING_MODAL = "HIDE_SET_RATING_MODAL";

export const CHANGE_RATING = "CHANGE_RATING";
