export const NAV_TO = "NAV_TO";
export const SET_ROUTE = "SET_ROUTE";

export const GET_ALL_PARTIES_SEND = "GET_ALL_PARTIES_SEND";
export const GET_ALL_PARTIES_FAILED = "GET_ALL_PARTIES_FAILED";
export const GET_ALL_PARTIES_SUCCESS = "GET_ALL_PARTIES_SUCCESS";

export const CREATE_PARTY_SEND = "CREATE_PARTY_SEND";
export const CREATE_PARTY_FAILED = "CREATE_PARTY_FAILED";
export const CREATE_PARTY_SUCCESS = "CREATE_PARTY_SUCCESS";

export const CHANGE_CREATE_PARTY_TITLE = "CHANGE_CREATE_PARTY_TITLE";
export const CHANGE_CREATE_PARTY_DESCRIPTION = "CHANGE_CREATE_PARTY_DESCRIPTION";
export const CHANGE_CREATE_PARTY_IDEOLOGY = "CHANGE_CREATE_PARTY_IDEOLOGY";

export const SHOW_CREATE_MODAL = "SHOW_CREATE_MODAL";
export const CLOSE_CREATE_MODAL = "CLOSE_CREATE_MODAL";