export const NAV_TO = "NAV_TO";
export const SET_ROUTE = "SET_ROUTE";

export const LOAD_ALL_USERS_SEND = "LOAD_ALL_USERS_SEND";
export const LOAD_ALL_USERS_FAILED = "LOAD_ALL_USERS_FAILED";
export const LOAD_ALL_USERS_SUCCESS = "LOAD_ALL_USERS_SUCCESS";

export const LOAD_USER_INFO_SEND = "LOAD_USER_INFO_SEND";
export const LOAD_USER_INFO_FAILED = "LOAD_USER_INFO_FAILED";
export const LOAD_USER_INFO_SUCCESS = "LOAD_USER_INFO_SUCCESS";

export const SHOW_ABOUT_USER = "SHOW_ABOUT_USER";
export const HIDE_ABOUT_USER = "HIDE_ABOUT_USER";

export const LOAD_ALL_PARTIES_SEND = "LOAD_ALL_PARTIES_SEND";
export const LOAD_ALL_PARTIES_FAILED = "LOAD_ALL_PARTIES_FAILED";
export const LOAD_ALL_PARTIES_SUCCESS = "LOAD_ALL_PARTIES_SUCCESS";

export const LOAD_PARTY_INFO_SEND = "LOAD_PARTY_INFO_SEND";
export const LOAD_PARTY_INFO_FAILED = "LOAD_PARTY_INFO_FAILED";
export const LOAD_PARTY_INFO_SUCCESS = "LOAD_PARTY_INFO_SUCCESS";

export const SHOW_ABOUT_PARTY = "SHOW_ABOUT_PARTY";
export const HIDE_ABOUT_PARTY = "HIDE_ABOUT_PARTY";

