module.exports = {
    EMPTY_PARTIES: "EMPTY_PARTIES",
    NO_PARTY_NAME: "NO_PARTY_NAME",
    NO_PARTY_DESCRIPTION: "NO_PARTY_DESCRIPTION",
    NO_PARTY_IDEOLOGY: "NO_PARTY_IDEOLOGY",
    NO_SUCH_PARTY: "NO_SUCH_PARTY",
};